name: CI/CD with EF Core and Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x

    - name: Build and Test
      run: |
        dotnet restore
        dotnet build
        dotnet test

    - name: Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Build Docker image
      run: |
        docker build -t sengkhimk/webapplication1 .
        docker tag sengkhimk/webapplication1 sengkhimk/webapplication1:latest
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: docker push sengkhimk/webapplication1:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: 3.1

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish "WebApplication1.csproj" -c Release -o /app/publish /p:UseAppHost=false

    - name: Test with .NET
      run: dotnet test

    - name: Deploy to SmarterASP.NET
      uses: jahbenjah/SmarterASP.NET-web-deploy@1.0.0
      with:
          website-name: sengkhimk-001-site1
          #server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: sengkhimk-001
          server-password: Password@168
          source-path: 'h:/root/home/sengkhimk-001/www'
          target-path: '/site1/'


