name: CI/CD with EF Core and Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x

    - name: Build and Test
      run: |
        dotnet restore
        dotnet build
        dotnet test

    - name: Build Docker image
      run: |
        docker build -t sengkhimk/webapplication1 .
        docker tag sengkhimk/webapplication1 sengkhimk/webapplication1:latest
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: docker push sengkhimk/webapplication1:latest

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish WebApplication1/WebApplication1.csproj --configuration Release --framework net7.0 --output ./publish --runtime win-x86 --self-contained true -p:PublishTrimmed=false -p:PublishSingleFile=false

    - name: Test with .NET
      run: dotnet test

    - name: SmarterASP.NET Web Deploy
      uses: jahbenjah/SmarterASP.NET-web-deploy@1.0.0.alpha.8
      with:
        website-name: site1
        server-computer-name: DESKTOP-GLV3PDG
        server-username: sengkhimk
        server-password: Password@168


