name: CI/CD with EF Core and Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x

    - name: Build and Test
      run: |
        dotnet restore
        dotnet build
        dotnet test

    - name: Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Build Docker image
      run: |
        docker build -t sengkhimk/webapplication1 .
        docker tag sengkhimk/webapplication1 sengkhimk/webapplication1:latest
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: docker push sengkhimk/webapplication1:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to SmarterASP
      env:
        SMARTERASP_FTP_SERVER: win5157.site4now.net
        SMARTERASP_FTP_USERNAME: sengkhimk-001
        SMARTERASP_FTP_PASSWORD: Password@168
      run: |
        wget http://www.ncftp.com/ncftp/ncftp-3.2.6/ncftp-3.2.6.tar.gz
        tar -zxvf ncftp-3.2.6.tar.gz
        cd ncftp-3.2.6
        ./ncftpput -u $SMARTERASP_FTP_USERNAME -p $SMARTERASP_FTP_PASSWORD $SMARTERASP_FTP_SERVER /wwwroot path/to/publish-folder/*

